<?php

#AUTOGENERATED BY HYBRIDAUTH 2.1.1-dev INSTALLER - Wednesday 23rd of July 2014 01:07:11 AM

/* !
 * HybridAuth
 * http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
 * (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
 */

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return
        array(
            
          // "base_url" => "http://presslist.test.bidnet.vc/index.php/user/login/oauth", 
            
           //"base_url" => "http://localhost/APL/index.php/user/login/oauth",
			"base_url" => "https://tompanther.arvixe.com/~webside/yetgroup.com/demo-webserver/APL/index.php/user/login/oauth", 
            "providers" => array(
                
//                //Local APP
               //"LinkedIn" => array(
                   //"enabled" => true,
                   //"keys" => array("key" => "771y4v85zbk8kt", "secret" => "4JkmTIpHPAjq1p1t")
               //),
                // Tompath App
                        "LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "77zho8cnt43619", "secret" => "IWYsGHsppcq7aqzN" ) 
			),
			
		// presslist.test App
   //                      "LinkedIn" => array ( 
			// 	"enabled" => true,
			// 	"keys"    => array ( "key" => "77om7tcf0jkc3j", "secret" => "TkMSZ5cWx7J3UbF2" ) 
			// ),	
//
                // openid providers
                // 
//			"OpenID" => array (
//				"enabled" => true
//			),
//
//			"AOL"  => array ( 
//				"enabled" => true 
//			),
//
//			"Yahoo" => array ( 
//				"enabled" => true,
//				"keys"    => array ( "id" => "", "secret" => "" )
//			),
//
//			"Google" => array ( 
//				"enabled" => true,
//				"keys"    => array ( "id" => "", "secret" => "" )
//			),
                //loca APP
//               "Facebook" => array(
//                   "enabled" => true,
//                   "keys" => array("id" => "470579799712118", "secret" => "603ece206500ba591cbd3aaba30281cc")
//               ),
                // Tompath App
                    "Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "1451324215128801", "secret" => "70c1925ce3498786a5c72ef9f35abcbf" )
			),
                 // presslist.test App
   //                  "Facebook" => array ( 
			// 	"enabled" => true,
			// 	"keys"    => array ( "id" => "692272174200953", "secret" => "028f733234c8de37496f6cf74cb5d9e0" )
			// ),
                
                
                //Local APP
//               "Twitter" => array(
//                   "enabled" => true,
//                   "keys" => array("key" => "0uvgR9TunBDD9ugV8ws46xYXb", "secret" => "tu0F0lybbPRBIL0qnbzWFfyqYqQkB6sBgJUlwBOUPEg5w7TBim")
//               ),
                //Tompath APP
            "Twitter" => array ( 
                        "enabled" => true,
                        "keys"    => array ( "key" => "2t6NN2LJlUHwJBom4zqLFSdQN", "secret" => "LGXUQOqGDlr4RJkc93ZjYK5bYMO6oBHcNy81i7zwIgW3DfHv85" ) 
                ),
//                //presslist.test App
            // "Twitter" => array ( 
            //             "enabled" => true,
            //             "keys"    => array ( "key" => "CV06awgBpE6ugaBZG1v7QvIcz", "secret" => "lDbMjE0M89KMbbk0JV4x095UrVW83N0rgiTu8tPAMnO6BjkZP6" ) 
            //     ),
                
//                
//                
//                
//			// windows live
//			"Live" => array ( 
//				"enabled" => true,
//				"keys"    => array ( "id" => "", "secret" => "" ) 
//			),
//
//			"MySpace" => array ( 
//				"enabled" => true,
//				"keys"    => array ( "key" => "", "secret" => "" ) 
//			),
//			"Foursquare" => array (
//				"enabled" => true,
//				"keys"    => array ( "id" => "", "secret" => "" ) 
//			),
            ),
            // if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
            "debug_mode" => false,
            "debug_file" => ""
);
